- filename: ./src/app/__init__.py
  content: |
    from .app import app

- filename: ./src/app/app.py
  content: |
    from fastapi import FastAPI
    from fastapi.staticfiles import StaticFiles
    from app.api.routes.root import router_root

    APP_NAME = "HyperPyText-App"  # You can customize this name
    APP_DESCRIPTION = "A FastAPI application created with HyperPyText"
    APP_VERSION = "0.1.0"

    app = FastAPI(
        title=APP_NAME,
        description=APP_DESCRIPTION,
        version=APP_VERSION
    )

    # Static file mounts
    app.mount('/assets', StaticFiles(directory='./src/assets'), name='assets')
    app.mount('/templates', StaticFiles(directory='./src/app/templates'), name='templates')

    # Router inclusion
    app.include_router(router_root)

    # You can add more app-wide configurations here, such as:
    # app.add_middleware(...)
    # app.add_exception_handler(...)
