filename: ./app.py
content: |
  from fastapi import FastAPI
  from fastapi.staticfiles import StaticFiles
  from api import router_root

  app = FastAPI()

  app.mount('/assets', StaticFiles(directory='assets'), name='assets')
  app.mount('/templates', StaticFiles(directory='templates'), name='templates')

  app.include_router(router_root)

