filename: ./src/app/app.py
content: |
  from fastapi import FastAPI
  from fastapi.staticfiles import StaticFiles
  from src.app.api import router_root

  app = FastAPI()

  app.mount('/assets', StaticFiles(directory='./src/assets'), name='assets')
  app.mount('/templates', StaticFiles(directory='./src/app/templates'), name='templates')

  app.include_router(router_root)
