filename: ./tailwind.config.js
content: |
  /** @type {import('tailwindcss').Config} */
  module.exports = {
    content: [
      "./templates/**/*.html",
      "./static/**/*.js",
      "./**/*.py"
    ],
    theme: {
      screens: {
        xs: '390px',
        sm: '435px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        xl2: '1536px',
        xl3: '1680px',
      },
      extend: {},
    },
    plugins: [],
  }

